AUTHOR_ID  = KPRCA
SERVICE_ID = 00015
CFLAGS     = -Os -g -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_SEED=5186923908517
POLLS_TESTING_SEED=289756392356

include /usr/share/cb-testing/cgc-cb.mk
