AUTHOR_ID  = CROMU
SERVICE_ID = 00007
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_COUNT = 100
POLLS_RELEASE_SEED = -702248071
POLLS_TESTING_COUNT = 900
POLLS_TESTING_SEED = 913573494

include /usr/share/cb-testing/cgc-cb.mk
