POLLS_RELEASE_SEED= -505578604
POLLS_TESTING_SEED= 1152975448
AUTHOR_ID  = CROMU
SERVICE_ID = 00013
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed
include /usr/share/cb-testing/cgc-cb.mk
