POLLS_RELEASE_SEED= 1801436218
POLLS_TESTING_SEED= -767607599
AUTHOR_ID  = YAN01
SERVICE_ID = 00008
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed -fno-rtti

include /usr/share/cb-testing/cgc-cb.mk
