AUTHOR_ID  = YAN01
SERVICE_ID = 00003
CFLAGS     = -O0 -g -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_SEED = 1341814549
POLLS_TESTING_SEED=53276895237

include /usr/share/cb-testing/cgc-cb.mk
