POLLS_TESTING_SEED= -710851069
AUTHOR_ID  = KPRCA
SERVICE_ID = 00004
CFLAGS     = -Ofast -ffast-math -g -Werror -Wno-overlength-strings -Wno-packed

POLLS_RELEASE_SEED = -11590114

include /usr/share/cb-testing/cgc-cb.mk
